export const BACKGROUND_ACTIONS = {
	// Characters
	GET_CHARACTERS: "GET_CHARACTERS",
	ADD_CHARACTER: "ADD_CHARACTER",
	UPDATE_CHARACTER: "UPDATE_CHARACTER",
	REMOVE_CHARACTER: "REMOVE_CHARACTER",

	// Character relationships
	GET_CHARACTER_RELATIONSHIPS: "GET_CHARACTER_RELATIONSHIPS",
	ADD_CHARACTER_RELATIONSHIP: "ADD_CHARACTER_RELATIONSHIP",
	UPDATE_CHARACTER_RELATIONSHIP: "UPDATE_CHARACTER_RELATIONSHIP",
	REMOVE_CHARACTER_RELATIONSHIP: "REMOVE_CHARACTER_RELATIONSHIP",

	// Novels
	GET_NOVELS: "GET_NOVELS",
	ADD_NOVEL: "ADD_NOVEL",
	UPDATE_NOVEL: "UPDATE_NOVEL",
	REMOVE_NOVEL: "REMOVE_NOVEL",

	// Current Novel
	GET_CURRENT_NOVEL: "GET_CURRENT_NOVEL",
	SET_CURRENT_NOVEL: "SET_CURRENT_NOVEL",
} as const;

export const CONTENT_ACTIONS = {
	TOAST: "TOAST",
	PROMPT: "PROMPT",
} as const;
